export const CAMPUSES = [
    "Agni College of Technology",
    "Amrita Vishwa Vidyapeetham",
    "Anna University",
    "BITS Pilani",
    "BITS Pilani - Goa",
    "BITS Pilani - Hyderabad",
    "College of Engineering, Pune (COEP)",
    "Delhi Technological University (DTU)",
    "Easwari Engineering College",
    "Hindustan Institute of Technology and Science",
    "IIIT Bangalore",
    "IIIT Hyderabad",
    "IIT Bombay",
    "IIT Delhi",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "Jadavpur University",
    "Karunya Institute of Technology and Sciences",
    "Manipal Institute of Technology",
    "Meenakshi Sundararajan Engineering College",
    "Netaji Subhas University of Technology (NSUT)",
    "NIT Calicut",
    "NIT Rourkela",
    "NIT Surathkal",
    "NIT Trichy",
    "NIT Warangal",
    "Panimalar Engineering College",
    "PSG College of Technology",
    "Rajalakshmi Engineering College",
    "SASTRA University",
    "Sathyabama Institute of Science and Technology",
    "Saveetha Engineering College",
    "SRM Institute of Science and Technology",
    "Sri Sairam Engineering College",
    "SSN College of Engineering",
    "St. Joseph's College of Engineering",
    "Thapar Institute of Engineering and Technology",
    "Vellore Institute of Technology (VIT)",
    "VIT University - Chennai"
].sort();
